In [1]:
### Library Import
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
# Function Imports
import sys
sys.path.append('/Users/mburley/TradingIndicators/Functions')  # Add the 'Functions' directory to the Python path
from IndicatorFunctions import import_stock_data, plot_function
from IndicatorFunctions import calculate_macd, calculate_rsi, calculate_cci, adx_mult_tickers

In [4]:
### Import Stock Data for the Ticker List
tickers = ['CELH', 'LI', 'AMD', 'TSM', 'BA', 'RDDT', 'ONCT', 'PFE', 'STT', 'MSAI', 'WNS', 'TSLA', 'TNON',
           'BTDR', 'RRGB', 'AVO', 'JPM', 'EL', 'CRDO', 'VC', 'BLK', 'APLD', 'LCID', 'ORCL', 'RIVN', 'RUN',
           'QS', 'GME', 'CISS', 'ALLR']
start_date = '2018-01-01'

stock_data = import_stock_data(tickers, start_date)
stock_data.tail()

[*********************100%%**********************]  30 of 30 completed

Price        Date Close                                                   \
Ticker             ALLR         AMD  APLD    AVO          BA         BLK
1586   2024-04-23  1.42  152.270004  2.93  11.38  169.179993  766.619995
1587   2024-04-24  1.37  151.740005  2.98  11.23  164.330002  762.799988
1588   2024-04-25  1.43  153.759995  3.00  11.47  166.809998  757.650024
1589   2024-04-26  1.46  157.399994  2.94  11.34  167.220001  762.880005
1590   2024-04-29  1.38  160.199997  2.71  11.46  173.490005  761.280029

Price                           ...        Low                       \
Ticker  BTDR       CELH   CISS  ...       RDDT   RIVN  RRGB     RUN
1586    6.71  72.029999  1.255  ...  41.821999  8.685  6.53   9.811
1587    6.48  72.000000  1.430  ...  42.450001  8.693  6.44   9.900
1588    6.46  71.639999  1.360  ...  40.849998  8.460  6.48   9.465
1589    6.35  73.160004  1.350  ...  42.650002  8.500  6.85   9.711
1590    6.03  73.730003  1.340  ...  45.849998  9.020  7.01  10.510

Price
Ticker        STT   TNON        TSLA         TSM          VC        WNS
1586    74.029999  0.710  141.110001  130.660004  108.260002  47.400002
1587    73.599998  0.720  157.509995  131.539993  108.989998  46.680000
1588    72.599998  0.729  158.360001  128.860001  105.190002  40.060001
1589    73.029999  0.710  166.369995  135.949997  110.949997  39.849998
1590    73.129997  0.730  184.539993  135.910004  111.059998  40.020000

[5 rows x 91 columns]

In [ ]:
###